# `modmap` section
# For key-to-key remapping (no combinations). Remapping a key to a modifier key (e.g. CapsLock to Control_L) is supported only in `modmap` section
modmap:
  - name: Make ⌘ act as Ctrl (except for Terminal app)
    application:
      not: gnome-terminal-server.Gnome-terminal
    remap:
      LeftCtrl: LeftMeta
      LeftMeta: LeftCtrl
      RightCtrl: RightMeta
      RightMeta: RightCtrl
# `keymap` section
# For remapping a sequence of key combinations to another sequence of key combinations
keymap:
  - name: Make ⌘← and ⌘→ work as Home and End (with Shift for selection)
    remap:
      Ctrl-Left: Home
      Ctrl-Right: End
      Shift-Ctrl-Left: Shift-Home
      Shift-Ctrl-Right: Shift-End
  - name: Delete word
    remap:
      Alt-Backspace: Ctrl-Backspace
  - name: Delete complete line # TODO - check on macOS. Not sure how to delete before and after cursor.
    application:
      not: gnome-terminal-server.Gnome-terminal
    remap:
      Ctrl-K: Ctrl-D
#  TODO: Next word
#  TODO: Previous word
  - name: Nautilus directory navigation and other
    application: 
      only: org.gnome.Nautilus.org.gnome.Nautilus
    remap:
      Ctrl-Up: Alt-Up
      Ctrl-Down: Alt-Down
      Ctrl-Backspace: Delete
      Shift-Ctrl-Dot: Ctrl-H
      Shift-Ctrl-G: Ctrl-L
  - name: Terminal copy and paste
    application: 
      only: gnome-terminal-server.Gnome-terminal
    remap:
      Super-C: Shift-Super-C
      Super-V: Shift-Super-V
  - name: Switch applications with Terminal active window
    application: 
      only: gnome-terminal-server.Gnome-terminal
    remap:
      Super-Tab: Ctrl-Tab
      Super-KEY_GRAVE: Ctrl-KEY_GRAVE
