keypress_delay_ms: 10

# `modmap` section
# For key-to-key remapping (no combinations). Remapping a key to a modifier key (e.g. CapsLock to Control_L) is supported only in `modmap` section
modmap:
  - name: Make ⌘ act as Ctrl
#    application:
#      not: gnome-terminal-server
    remap:
      LeftCtrl: LeftMeta
      LeftMeta: LeftCtrl
      RightCtrl: RightMeta
      RightMeta: RightCtrl
# `keymap` section
# For remapping a sequence of key combinations to another sequence of key combinations
keymap:
#  - name: Test
#    remap:
#      Shift-A: b
  - name: Make ⌘← and ⌘→ work as Home and End (with Shift for selection)
    remap:
      Ctrl-Left: Home
      Ctrl-Right: End
      Shift-Ctrl-Left: Shift-Home
      Shift-Ctrl-Right: Shift-End
  - name: Delete word
    remap:
      Alt-Backspace: Ctrl-Backspace
  - name: Delete complete line # TODO - check on macOS. Not sure how to delete before and after cursor.
    application:
      not: gnome-terminal-server
    remap:
      Ctrl-K: Ctrl-D
#  TODO: Next word
#  TODO: Previous word
  - name: Norg.gnome.Nautilus directory navigation and other
    application:
      only: org.gnome.Nautilus
    remap:
      Ctrl-Up: Alt-Up
      Ctrl-Down: Alt-Down
      Ctrl-Backspace: Delete
      Shift-Ctrl-Dot: Ctrl-H
      Shift-Ctrl-G: Ctrl-L
  - name: Tgnome-terminal-server copy and paste and window management
    application:
      only: gnome-terminal-server
    remap:
      Ctrl-C: Shift-Super-C
      Ctrl-V: Shift-Super-V
      Ctrl-T: Shift-Super-T
      Ctrl-N: Shift-Super-N
      Ctrl-W: Shift-Super-W
      Ctrl-Q: Shift-Super-Q
      Ctrl-F: Shift-Super-F
  - name: Tgnome-terminal-server interrupt
    application:
      only: gnome-terminal-server
    remap:
      Super-C: Ctrl-C
  - name: Tgnome-terminal-server special combinations for nano editor (keycombiner.com/collections/nano/)
    application:
      only: gnome-terminal-server
    remap:
#      Interferes with GNOME close window - not sure how to work around
      Super-Q: Ctrl-Q
      Super-W: Ctrl-W
      Super-E: Ctrl-E
      Super-E: Ctrl-R
      Super-T: Ctrl-T
      Super-Y: Ctrl-Y
      Super-U: Ctrl-U
      Super-O: Ctrl-O
      Super-P: Ctrl-P
      Super-KEY_RIGHTBRACE: Ctrl-KEY_RIGHTBRACE
      Super-A: Ctrl-A
      Super-S: Ctrl-S
# How to implement a tgnome-terminal-server key combination that conflicts with some GNOME keybinding?
# A. Unset the default via gsettings in install.sh and do not use this GNOME keybinding
# - or -
# B. Make a script similar to the one below. Script unsets the GNOME keybinding, then sends keys, then restores keybinding back.
      Super-D:
        launch: ["sh", "/home/petrstepanov/.local/bin/tgnome-terminal-server-ctrl-d.sh"]
      Super-F: Ctrl-F
      Super-G: Ctrl-G
      Super-H: Ctrl-H
      Super-J: Ctrl-J
      Super-K: Ctrl-K
      Super-L: Ctrl-L
      Super-Z: Ctrl-Z
      Super-X: Ctrl-X
#     Ctrl-C declared in previous sections
#     Super-C: Ctrl-C
      Super-V: Ctrl-V
      Super-B: Ctrl-B
      Super-N: Ctrl-N
      Super-KEY_SLASH: Ctrl-KEY_SLASH
