# `modmap` section
# For key-to-key remapping (no combinations). Remapping a key to a modifier key (e.g. CapsLock to Control_L) is supported only in `modmap` section
modmap:
  - name: Make ⌘ act as Ctrl (except for Terminal app)
    remap:
      LeftCtrl: LeftMeta
      LeftMeta: LeftCtrl
      RightCtrl: RightMeta
      RightMeta: RightCtrl
# `keymap` section
# For remapping a sequence of key combinations to another sequence of key combinations
keymap:
  - name: Make ⌘← and ⌘→ work as Home and End (with Shift for selection)
    remap:
      Ctrl-Left: Home
      Ctrl-Right: End
      Shift-Ctrl-Left: Shift-Home
      Shift-Ctrl-Right: Shift-End
  - name: Delete word
    remap:
      Alt-Backspace: Ctrl-Backspace
  - name: Delete complete line # TODO - check on macOS. Not sure how to delete before and after cursor.
    application:
      not: gnome-terminal-server.Gnome-terminal
    remap:
      Ctrl-K: Ctrl-D
#  TODO: Next word
#  TODO: Previous word
  - name: Nautilus directory navigation and other
    application: 
      only: org.gnome.Nautilus.org.gnome.Nautilus
    remap:
      Ctrl-Up: Alt-Up
      Ctrl-Down: Alt-Down
      Ctrl-Backspace: Delete
      Shift-Ctrl-Dot: Ctrl-H
      Shift-Ctrl-G: Ctrl-L
  - name: Terminal copy and paste and window management
    application: 
      only: gnome-terminal-server.Gnome-terminal
    remap:
      Ctrl-C: Shift-Super-C
      Ctrl-V: Shift-Super-V
      Ctrl-T: Shift-Super-T
      Ctrl-N: Shift-Super-N
      Ctrl-W: Shift-Super-W
      Ctrl-Q: Shift-Super-Q
  - name: Terminal interrupt
    application: 
      only: gnome-terminal-server.Gnome-terminal
    remap:
      Super-C: Ctrl-C
  - name: Terminal special combinations for keycombiner.com/collections/nano/
    application: 
      only: gnome-terminal-server.Gnome-terminal
    remap:
#      Interferes with GNOME close window - not sure how to work around
      Super-Q: Ctrl-Q    
      Super-W: Ctrl-W    
      Super-E: Ctrl-E
      Super-E: Ctrl-R      
      Super-T: Ctrl-T
      Super-Y: Ctrl-Y
      Super-U: Ctrl-U
      Super-O: Ctrl-O
      Super-P: Ctrl-P
      Super-A: Ctrl-A
      Super-KEY_SLASH: Ctrl-KEY_SLASH
#      Super-T: 
#        launch: ["sh", "/home/petrstepanov/.local/bin/terminal-ctrl-t.sh"]
#      Super-W: 
#        launch: ["sh", "/home/petrstepanov/.local/bin/terminal-ctrl-w.sh"]
      Super-X: Ctrl-X
